# Generated by Django 5.2.3 on 2025-06-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('type_probleme', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('localisation', models.CharField(max_length=255)),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
